# NumPy 50 Questions Assignment

This notebook solves all 50 practical NumPy questions step-by-step using the dataset **`cleaned_tickets.csv`**.

- **Dataset Path**: `D:\AI ML Assignments\cleaned_tickets.csv`
- **Key Libraries**: `numpy`, `pandas`

### 1. Import NumPy and print its version.


In [1]:
import numpy as np
import pandas as pd

# Print NumPy version
print(f"NumPy Version: {np.__version__}")


NumPy Version: 2.5.3


### 2. Make an array from the hours logged column.


In [2]:
# Load dataset
csv_path = r"D:\AI ML Assignments\cleaned_tickets.csv"
df = pd.read_csv(csv_path, low_memory=False)

# Make an array from the 'hours_logged' column
hours = df['hours_logged'].to_numpy()

print("Array created from 'hours_logged'.")
print("First 5 values:", hours[:5])


Array created from 'hours_logged'.
First 5 values: [  nan  1.34  7.   34.63 12.76]


### 3. Print the shape, the size and the data type of that array.


In [3]:
# Print shape, size, and data type of the hours array
print("Shape:    ", hours.shape)
print("Size:     ", hours.size)
print("Data type:", hours.dtype)


Shape:     (48123,)
Size:      48123
Data type: float64


### 4. Make an array of the numbers 1 to 50 using arange.


In [4]:
# Array from 1 to 50
arr_1_to_50 = np.arange(1, 51)

print("Array of numbers 1 to 50:")
print(arr_1_to_50)


Array of numbers 1 to 50:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


### 5. Make 10 evenly spaced numbers between 0 and 100 using linspace.


In [5]:
# 10 evenly spaced numbers between 0 and 100
spaced_numbers = np.linspace(0, 100, 10)

print("10 evenly spaced numbers between 0 and 100:")
print(spaced_numbers)


10 evenly spaced numbers between 0 and 100:
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


### 6. Make an array of 10 zeros and an array of 10 ones.


In [6]:
# 10 zeros and 10 ones
zeros_arr = np.zeros(10)
ones_arr = np.ones(10)

print("Array of 10 zeros:", zeros_arr)
print("Array of 10 ones: ", ones_arr)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 7. Make a 3 by 3 array of random numbers using seed 42.


In [7]:
# Set random seed to 42 for reproducibility
np.random.seed(42)

# Generate 3x3 array of random numbers
random_3x3 = np.random.rand(3, 3)

print("3x3 array of random numbers (seed 42):")
print(random_3x3)


3x3 array of random numbers (seed 42):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


### 8. Make a 2-D array from the hours logged and billing rate columns.


In [8]:
# Extract billing rate column as a numpy array
billing_rate = df['billing_rate_(usd)'].to_numpy()

# Combine hours logged and billing rate columns into a 2-D array
arr_2d = np.column_stack((hours, billing_rate))

print("2-D array created.")
print("Shape of 2-D array:", arr_2d.shape)
print("First 5 rows [hours_logged, billing_rate]:")
print(arr_2d[:5])


2-D array created.
Shape of 2-D array: (48123, 2)
First 5 rows [hours_logged, billing_rate]:
[[  nan 39.45]
 [ 1.34 33.15]
 [ 7.   48.1 ]
 [34.63 52.98]
 [12.76 22.9 ]]


### 9. Print how many dimensions that 2-D array has.


In [9]:
# Check number of dimensions using ndim
print("Number of dimensions:", arr_2d.ndim)


Number of dimensions: 2


### 10. Print the first 5 values of the hours array.


In [10]:
# First 5 values
print("First 5 values of hours array:", hours[:5])


First 5 values of hours array: [  nan  1.34  7.   34.63 12.76]


### 11. Print the last 5 values of the hours array.


In [11]:
# Last 5 values
print("Last 5 values of hours array:", hours[-5:])


Last 5 values of hours array: [50.  4. 47.  2. nan]


### 12. Print every second value from the first 20 values.


In [12]:
# Slicing with step 2 from the first 20 elements
print("Every second value from the first 20 values:")
print(hours[:20:2])


Every second value from the first 20 values:
[   nan   7.    12.76    nan   1.66    nan  11.63  28.     0.59 253.85]


### 13. Reverse the array.


In [13]:
# Reverse the hours array
hours_reversed = hours[::-1]

print("Reversed array (first 5 elements):", hours_reversed[:5])
print("Reversed array (last 5 elements): ", hours_reversed[-5:])


Reversed array (first 5 elements): [nan  2. 47.  4. 50.]
Reversed array (last 5 elements):  [12.76 34.63  7.    1.34   nan]


### 14. Find the sum of the hours array.


In [14]:
# Standard sum (returns NaN if missing values exist)
print("Standard np.sum(hours):  ", np.sum(hours))

# Sum ignoring NaN values
print("Sum ignoring NaN (np.nansum):", np.nansum(hours))


Standard np.sum(hours):   nan
Sum ignoring NaN (np.nansum): 2290016.55


### 15. Find the mean, the minimum and the maximum of the hours array.


In [15]:
# Computing mean, min, and max (ignoring NaN)
mean_val = np.nanmean(hours)
min_val = np.nanmin(hours)
max_val = np.nanmax(hours)

print(f"Mean (ignoring NaN):    {mean_val:.2f}")
print(f"Minimum (ignoring NaN): {min_val}")
print(f"Maximum (ignoring NaN): {max_val}")


Mean (ignoring NaN):    63.17
Minimum (ignoring NaN): -12.5
Maximum (ignoring NaN): 9888.01


### 16. Find the standard deviation.


In [16]:
# Standard deviation (ignoring NaN)
std_dev = np.nanstd(hours)
print(f"Standard deviation (ignoring NaN): {std_dev:.4f}")


Standard deviation (ignoring NaN): 493.3143


### 17. Find the median.


In [17]:
# Median (ignoring NaN)
median_val = np.nanmedian(hours)
print(f"Median (ignoring NaN): {median_val:.2f}")


Median (ignoring NaN): 13.10


### 18. Count how many values are missing in the array.


In [18]:
# Count NaN values using np.isnan()
missing_count = np.isnan(hours).sum()
print(f"Number of missing values in hours array: {missing_count}")


Number of missing values in hours array: 11870


### 19. Find the mean while ignoring the missing values.


In [19]:
# Mean ignoring missing values using np.nanmean()
mean_without_nan = np.nanmean(hours)
print(f"Mean ignoring missing values: {mean_without_nan:.4f}")


Mean ignoring missing values: 63.1676


### 20. Replace all the missing values with 0.


In [20]:
# Replace NaN with 0
hours_clean = np.where(np.isnan(hours), 0.0, hours)

print("Count of missing values after replacement:", np.isnan(hours_clean).sum())
print("First 5 values after replacement:", hours_clean[:5])


Count of missing values after replacement: 0
First 5 values after replacement: [ 0.    1.34  7.   34.63 12.76]


### 21. Count how many values are greater than 100.


In [21]:
# Count of values greater than 100
gt_100_count = np.sum(hours_clean > 100)
print(f"Number of values greater than 100: {gt_100_count}")


Number of values greater than 100: 1588


### 22. Show only the values that are greater than 100.


In [22]:
# Filter values greater than 100
values_gt_100 = hours_clean[hours_clean > 100]

print(f"Total values > 100: {len(values_gt_100)}")
print("Sample (first 10 values > 100):")
print(values_gt_100[:10])


Total values > 100: 1588
Sample (first 10 values > 100):
[ 253.85  128.   1900.66  133.35  373.68 5000.    723.5   101.04  152.
  311.49]


### 23. Show the values that are between 10 and 50.


In [23]:
# Filter values between 10 and 50 (inclusive)
between_10_and_50 = hours_clean[(hours_clean >= 10) & (hours_clean <= 50)]

print(f"Total values between 10 and 50: {len(between_10_and_50)}")
print("Sample (first 10 values between 10 and 50):")
print(between_10_and_50[:10])


Total values between 10 and 50: 17101
Sample (first 10 values between 10 and 50):
[34.63 12.76 15.3  11.63 28.   10.16 32.71 30.84 18.   31.44]


### 24. Count how many values are negative.


In [24]:
# Count negative values
negative_count = np.sum(hours_clean < 0)
print(f"Number of negative values: {negative_count}")


Number of negative values: 136


### 25. Replace all the negative values with 0.


In [25]:
# Replace negative values with 0
hours_clean = np.where(hours_clean < 0, 0.0, hours_clean)

print("Negative values after replacement:", np.sum(hours_clean < 0))


Negative values after replacement: 0


### 26. Sort the array from smallest to largest.


In [26]:
# Sort the array in ascending order
hours_sorted = np.sort(hours_clean)

print("First 5 smallest values:", hours_sorted[:5])
print("Last 5 largest values: ", hours_sorted[-5:])


First 5 smallest values: [0. 0. 0. 0. 0.]
Last 5 largest values:  [8760.   8760.   8760.   9888.01 9888.01]


### 27. Find the position of the largest value.


In [27]:
# Position of the largest value using np.argmax()
max_pos = np.argmax(hours_clean)

print(f"Position (index) of largest value: {max_pos}")
print(f"Largest value at this index:       {hours_clean[max_pos]}")


Position (index) of largest value: 10041
Largest value at this index:       9888.01


### 28. Find the position of the smallest value.


In [28]:
# Position of the smallest value using np.argmin()
min_pos = np.argmin(hours_clean)

print(f"Position (index) of smallest value: {min_pos}")
print(f"Smallest value at this index:      {hours_clean[min_pos]}")


Position (index) of smallest value: 0
Smallest value at this index:      0.0


### 29. Find the 5 largest values.


In [29]:
# Find the 5 largest values
five_largest = np.sort(hours_clean)[-5:][::-1]

print("The 5 largest values in hours array:")
print(five_largest)


The 5 largest values in hours array:
[9888.01 9888.01 8760.   8760.   8760.  ]


### 30. Round every value to 1 decimal place.


In [30]:
# Round every value to 1 decimal place
hours_rounded = np.round(hours_clean, 1)

print("First 10 values rounded to 1 decimal place:")
print(hours_rounded[:10])


First 10 values rounded to 1 decimal place:
[ 0.   1.3  7.  34.6 12.8 15.3  0.   9.   1.7  0. ]


### 31. Multiply every value by 2.


In [31]:
# Vectorized multiplication by 2
hours_mult_2 = hours_clean * 2

print("First 10 values multiplied by 2:")
print(hours_mult_2[:10])


First 10 values multiplied by 2:
[ 0.    2.68 14.   69.26 25.52 30.6   0.   18.    3.32  0.  ]


### 32. Add 10 to every value.


In [32]:
# Vectorized addition of 10
hours_plus_10 = hours_clean + 10

print("First 10 values after adding 10:")
print(hours_plus_10[:10])


First 10 values after adding 10:
[10.   11.34 17.   44.63 22.76 25.3  10.   19.   11.66 10.  ]


### 33. Multiply the hours array by the billing rate array.


In [33]:
# Handle any missing/negative values in billing rate as well
rate_clean = np.where(np.isnan(billing_rate), 0.0, billing_rate)
rate_clean = np.where(rate_clean < 0, 0.0, rate_clean)

# Element-wise multiplication
billed_amount = hours_clean * rate_clean

print("First 10 values of (hours * billing rate):")
print(billed_amount[:10])


First 10 values of (hours * billing rate):
[   0.       44.421   336.7    1834.6974  292.204  1828.35      0.
  432.54    120.1342    0.    ]


### 34. Check whether the two arrays have the same length.


In [34]:
# Check lengths of hours and billing rate arrays
has_same_length = (len(hours_clean) == len(rate_clean))

print(f"Hours array length:        {len(hours_clean)}")
print(f"Billing rate array length: {len(rate_clean)}")
print(f"Do both arrays have the same length? {has_same_length}")


Hours array length:        48123
Billing rate array length: 48123
Do both arrays have the same length? True


### 35. Use np.where to mark values above 24 as slow and the rest as fast.


In [35]:
# Classify hours: > 24 is 'slow', otherwise 'fast'
speed_status = np.where(hours_clean > 24, "slow", "fast")

print("First 10 values marked as slow/fast:")
print(speed_status[:10])
print(f"Total 'slow' tickets: {np.sum(speed_status == 'slow')}")
print(f"Total 'fast' tickets: {np.sum(speed_status == 'fast')}")


First 10 values marked as slow/fast:
['fast' 'fast' 'fast' 'slow' 'fast' 'fast' 'fast' 'fast' 'fast' 'fast']
Total 'slow' tickets: 11737
Total 'fast' tickets: 36386


### 36. Make an array of the unique priority values.


In [36]:
# Extract unique priority values (handling missing entries as 'Missing')
priority_arr = df['priority'].fillna('Missing').to_numpy(dtype=str)
unique_priorities = np.unique(priority_arr)

print("Unique priority values:")
print(unique_priorities)


Unique priority values:
[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'Missing' 'P1' 'P1 - Critical' 'P2' 'P3'
 'P4' 'PRIORITY' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


### 37. Count how many times each unique priority value appears.


In [37]:
# Count occurrences of each unique priority
unique_vals, counts = np.unique(priority_arr, return_counts=True)

print(f"{'Priority Value':<20} | {'Count':>10}")
print("-" * 34)
for val, count in zip(unique_vals, counts):
    print(f"{val:<20} | {count:>10}")


Priority Value       |      Count
----------------------------------
                     |         95
-                    |        107
--                   |        107
1                    |       1931
2                    |       1966
3                    |       1934
4                    |       1919
?                    |         85
CRITICAL             |       1993
Critical             |       2000
HIGH                 |       1950
High                 |       2003
LOW                  |       1945
Low                  |       1840
MEDIUM               |       1949
Medium               |       1941
Missing              |        832
P1                   |       1891
P1 - Critical        |       1969
P2                   |       1907
P3                   |       1950
P4                   |       1880
PRIORITY             |          1
high                 |       1971
low                  |       1950
medium               |       2023
missing              |        125
na           

### 38. Take the first 100 values and reshape them into a 10 by 10 array.


In [38]:
# Take first 100 values and reshape into 10x10
arr_10x10 = hours_clean[:100].reshape(10, 10)

print("Shape of reshaped array:", arr_10x10.shape)
print("10 by 10 array:")
print(arr_10x10)


Shape of reshaped array: (10, 10)
10 by 10 array:
[[0.00000e+00 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
  0.00000e+00 9.00000e+00 1.66000e+00 0.00000e+00]
 [0.00000e+00 1.44000e+00 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01
  5.90000e-01 7.00000e+00 2.53850e+02 4.20000e+00]
 [5.08100e+01 8.01000e+00 6.79400e+01 0.00000e+00 3.27100e+01 0.00000e+00
  6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00]
 [1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01 0.00000e+00 1.30000e+01
  3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00]
 [0.00000e+00 3.92000e+00 2.02200e+01 2.41500e+01 8.40000e+01 0.00000e+00
  2.70000e+01 0.00000e+00 4.00000e+00 2.76000e+00]
 [1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01 5.00000e+00 1.14100e+01
  0.00000e+00 1.80000e+01 1.28000e+02 1.54000e+01]
 [1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02 0.00000e+00
  4.00000e+00 0.00000e+00 2.00000e+00 0.00000e+00]
 [2.05100e+01 1.13300e+01 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00
 

### 39. Transpose that 10 by 10 array.


In [39]:
# Transpose the 10x10 array
arr_transposed = arr_10x10.T

print("Shape of transposed array:", arr_transposed.shape)
print("Transposed 10 by 10 array:")
print(arr_transposed)


Shape of transposed array: (10, 10)
Transposed 10 by 10 array:
[[0.00000e+00 0.00000e+00 5.08100e+01 1.80000e+01 0.00000e+00 1.12600e+01
  1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01]
 [1.34000e+00 1.44000e+00 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01
  4.00000e+00 1.13300e+01 1.78600e+01 1.09100e+01]
 [7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00 2.02200e+01 5.26000e+00
  3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00]
 [3.46300e+01 7.23100e+01 0.00000e+00 2.44600e+01 2.41500e+01 1.40000e+01
  9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00]
 [1.27600e+01 2.80000e+01 3.27100e+01 0.00000e+00 8.40000e+01 5.00000e+00
  1.33350e+02 2.29700e+01 0.00000e+00 3.73680e+02]
 [1.53000e+01 1.01600e+01 0.00000e+00 1.30000e+01 0.00000e+00 1.14100e+01
  0.00000e+00 0.00000e+00 2.00000e+01 1.13800e+01]
 [0.00000e+00 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01 0.00000e+00
  4.00000e+00 0.00000e+00 6.00000e+00 3.36700e+01]
 [9.00000e+00 7.00000e+00 3.08400e+01 1.15100e+01 0.00000e+00 

### 40. Flatten it back into a 1-D array.


In [40]:
# Flatten the array back to 1-D
arr_flattened = arr_transposed.flatten()

print("Shape of flattened array:", arr_flattened.shape)
print("First 10 values of flattened array:")
print(arr_flattened[:10])


Shape of flattened array: (100,)
First 10 values of flattened array:
[   0.      0.     50.81   18.      0.     11.26 1900.66   20.51   19.17
   13.  ]


### 41. Join two arrays together using np.concatenate.


In [41]:
# Split sample arrays and concatenate them
sub_arr1 = hours_clean[:5]
sub_arr2 = hours_clean[5:10]

concatenated_arr = np.concatenate((sub_arr1, sub_arr2))

print("Array 1:      ", sub_arr1)
print("Array 2:      ", sub_arr2)
print("Concatenated: ", concatenated_arr)


Array 1:       [ 0.    1.34  7.   34.63 12.76]
Array 2:       [15.3   0.    9.    1.66  0.  ]
Concatenated:  [ 0.    1.34  7.   34.63 12.76 15.3   0.    9.    1.66  0.  ]


### 42. Split an array into 5 equal parts.


In [42]:
# np.split requires equal division. Taking the first 50 values (50 / 5 = 10 elements per part):
parts = np.split(hours_clean[:50], 5)

print("Split first 50 values into 5 equal parts (10 elements each):")
for idx, part in enumerate(parts, 1):
    print(f"Part {idx}: {part}")

# For the entire dataset (length 48,123 is not divisible by 5), np.array_split is used:
parts_all = np.array_split(hours_clean, 5)
print(f"\nFull dataset split with np.array_split into 5 parts with sizes: {[len(p) for p in parts_all]}")


Split first 50 values into 5 equal parts (10 elements each):
Part 1: [ 0.    1.34  7.   34.63 12.76 15.3   0.    9.    1.66  0.  ]
Part 2: [  0.     1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]
Part 3: [50.81  8.01 67.94  0.   32.71  0.    6.91 30.84  3.51  4.34]
Part 4: [18.   31.44  3.42 24.46  0.   13.   30.02 11.51 63.02  1.03]
Part 5: [ 0.    3.92 20.22 24.15 84.    0.   27.    0.    4.    2.76]

Full dataset split with np.array_split into 5 parts with sizes: [9625, 9625, 9625, 9624, 9624]


### 43. Find the 25th, 50th and 75th percentile.


In [43]:
# Calculate percentiles
p25, p50, p75 = np.percentile(hours_clean, [25, 50, 75])

print(f"25th Percentile (Q1):             {p25:.2f}")
print(f"50th Percentile (Median / Q2):     {p50:.2f}")
print(f"75th Percentile (Q3):             {p75:.2f}")


25th Percentile (Q1):             0.00
50th Percentile (Median / Q2):     6.57
75th Percentile (Q3):             23.62


### 44. Find the cumulative sum of the first 20 values.


In [44]:
# Cumulative sum of first 20 values
cumsum_20 = np.cumsum(hours_clean[:20])

print("First 20 values:")
print(hours_clean[:20])
print("\nCumulative sum of first 20 values:")
print(cumsum_20)


First 20 values:
[  0.     1.34   7.    34.63  12.76  15.3    0.     9.     1.66   0.
   0.     1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]

Cumulative sum of first 20 values:
[  0.     1.34   8.34  42.97  55.73  71.03  71.03  80.03  81.69  81.69
  81.69  83.13  94.76 167.07 195.07 205.23 205.82 212.82 466.67 470.87]


### 45. Find the difference between each value and the one before it using np.diff.


In [45]:
# Difference between consecutive values
diff_values = np.diff(hours_clean[:20])

print("First 20 values:")
print(hours_clean[:20])
print("\nConsecutive differences (np.diff):")
print(diff_values)


First 20 values:
[  0.     1.34   7.    34.63  12.76  15.3    0.     9.     1.66   0.
   0.     1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]

Consecutive differences (np.diff):
[   1.34    5.66   27.63  -21.87    2.54  -15.3     9.     -7.34   -1.66
    0.      1.44   10.19   60.68  -44.31  -17.84   -9.57    6.41  246.85
 -249.65]


### 46. Keep every value inside the range 0 to 100 using np.clip.


In [46]:
# Clip values to range [0, 100]
clipped_hours = np.clip(hours_clean, 0, 100)

print(f"Minimum in clipped array: {np.min(clipped_hours)}")
print(f"Maximum in clipped array: {np.max(clipped_hours)}")
print("First 10 clipped values:")
print(clipped_hours[:10])


Minimum in clipped array: 0.0
Maximum in clipped array: 100.0
First 10 clipped values:
[ 0.    1.34  7.   34.63 12.76 15.3   0.    9.    1.66  0.  ]


### 47. Convert the array to whole numbers.


In [47]:
# Convert array to integer whole numbers
whole_numbers = hours_clean.astype(int)

print("Data type:", whole_numbers.dtype)
print("First 10 whole numbers:")
print(whole_numbers[:10])


Data type: int64
First 10 whole numbers:
[ 0  1  7 34 12 15  0  9  1  0]


### 48. Copy the array, change one value in the copy, and show that the original did not change.


In [48]:
# Create an explicit copy
hours_copy = hours_clean.copy()

# Modify first value in the copy
hours_copy[0] = 999999.0

print(f"Original array value at index 0: {hours_clean[0]}")
print(f"Copied array value at index 0:   {hours_copy[0]}")
print(f"Did the original array change?   {hours_clean[0] == 999999.0}")
print("Conclusion: Original array remained unchanged.")


Original array value at index 0: 0.0
Copied array value at index 0:   999999.0
Did the original array change?   False
Conclusion: Original array remained unchanged.


### 49. Save the array to a .npy file and load it back.


In [49]:
# Save array to .npy format
npy_file = "hours_logged.npy"
np.save(npy_file, hours_clean)
print(f"Array successfully saved to '{npy_file}'.")

# Load array back
loaded_hours = np.load(npy_file)
print(f"Array successfully loaded from '{npy_file}'.")

# Verify equality
is_identical = np.array_equal(hours_clean, loaded_hours)
print(f"Are original and loaded arrays identical? {is_identical}")


Array successfully saved to 'hours_logged.npy'.
Array successfully loaded from 'hours_logged.npy'.
Are original and loaded arrays identical? True


### 50. Find the total revenue using np.dot on the hours array and the rate array.


In [50]:
# Compute dot product: sum of (hours * billing_rate)
total_revenue = np.dot(hours_clean, rate_clean)

print(f"Total Revenue: ${total_revenue:,.2f}")


Total Revenue: $175,109,598.60
